### ISSUE TITLE
Support IPv6 on the ESP32

### ISSUE THREAD

**Issue by MichaelDvP** [nomis/mcu-uuid-syslog#2]
The changelog indicates that there is IPv6 support since v2.0.2, but usage example is only with IPv4. Is there a doc or implementation to see how to send to a IPv6 syslog-server?

**Comment by proddy** [comment]
on ESP32 specifically. The code works for ESP8266 and IPv6

**Comment by nomis** [comment]
The API takes an `IPAddress` which has a `fromString()` function for IPv6.

I don't have an ESP32 to test with. I'd start by finding out if `SyslogService::can_transmit()` is working correctly on the ESP32.

What addresses are assigned to the ESP32 and what address are you sending to? There's some logic in there that makes some assumptions that probably need to be relaxed about which address scopes can communicate with each other (it is trying to wait for a global address to be assigned before sending packets to one).

**Comment by MichaelDvP** [comment]
Syslog works fine with esp32. I've tried this:
```
    IPAddress   addr;
    IPv6Address addrv6;
    if (addr.fromString(syslog_host_.c_str())) {
    } else if (addrv6.fromString(syslog_host_.c_str())) {
        addr = addrv6;
    } else {
        WiFi.hostByName(syslog_host_.c_str(), addr);
    }
    syslog_.destination(addr, syslog_port_);
```
working for ipv4 adresses and names for syslog_host, but not for ipv6. 
`syslog_host = "192.168.0.8";` works, 
`syslog_host = "raspberrypi";` works,
`syslog_host = "fd00::f5f9:a756:10fa:3cfe";` does not work.
all the same syslog host.
passing  `addrv6` to destination is not possible.

**Comment by nomis** [comment]
Arduino has an `IPAddress` class that only supports IPv4.

The ESP8266 extends the `IPAddress` class to support IPv4 and IPv6.

The ESP32 splits this into `IPAddress` and `IPv6Address`, presumably without realising that this makes everything more complicated.

**Comment by nomis** [comment]
This is a really inconvenient implementation to use... https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/IPv6Address.cpp#L75-L90

**Comment by nomis** [comment]
I'm inclined to ask for the ESP32 implementation to be fixed instead.

This just causes many other problems like the API changing between ESP32 and non-ESP32. The `destination()` function can only have one return type. To fix that I'd need to make a wrapper type and that's not much better because the API would still be different on ESP32 devices from ESP8266 devices.

**Comment by nomis** [comment]
The `Udp` library doesn't support `IPv6Address`: https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/Udp.h#L53

**Comment by MichaelDvP** [comment]
Thank you very much for clearification. I think you can also close this for now.
