### ISSUE TITLE
Use RFC Message Structure

### ISSUE THREAD

**Issue by stevenengland** [nomis/mcu-uuid-syslog#4]
Hi, first of all, great work, thank you.

It would be helfpul if you could change the structure of the messages according to RFC.

The current structure is as follows:
`<134>1 - <hostname> - - - - ﻿000+00:01:24.661 I 5: [SetupMqtt] # Connected!`

Should be something like:
`<27>Mar 28 06:15:01 <hostname> eclipse-mosquitto/mosquitto/f493 1648448101: New client connected from 192.168.2.224:49197 as /xyz/123 (p2, c1, k15, u'iot_device').`

**Comment by nomis** [comment]
The current message format looks like this:
`<118>1 2022-03-28T06:58:50.833400Z hostname - - - - 028+13:41:05.759 I 824: [shell] User session closed on console pty0`

Which part of this do you think doesn't match [RFC5424](https://datatracker.ietf.org/doc/html/rfc5424#page-8)?

[RFC3164](https://datatracker.ietf.org/doc/html/rfc3164) is [obsoleted by RFC5254](https://datatracker.ietf.org/doc/html/rfc5424#page-4).

One of the advantages of RFC5254 is being able to omit fields like the timestamp (when it is unknown) and the hostname (when it isn't set).

**Comment by stevenengland** [comment]
Hi, thank you for coming back to me so fast.

I had a look into the source and it should work exactly as you said. But the format I provided ("current structure") above is what I actually receive from the device. What might be the reason for that, what can I check?

**Comment by nomis** [comment]
The timestamp is `-` because your device doesn't have the time set (i.e. it's near 1970). The `-` is valid syntax so your syslog server should accept it.

If you configure SNTP the time will then be available.

**Comment by stevenengland** [comment]
Ahhh, now I got the whole picture. I now use the code from [HERE](https://github.com/SensorsIot/NTP-time-for-ESP8266-and-ESP32/blob/master/NTP_Example/NTP_Example.ino) to sync the time and the logging finally works. Thanks! :)
